Repository aclavio/marklogic-state-conductor, pull requests merged in 2020-07, with the labels that each got.

#103 added the executionTime to the state conductor provenance
  build.gradle
  state-conductor-example/src/test/ml-modules/root/test/suites/StateConductorSuite/provenanceTests.sjs
  state-conductor-modules/src/main/ml-modules/root/state-conductor/state-conductor.sjs
Labels: enhancement

#110 use database specific server fields for storing registered query.
  state-conductor-modules/src/main/ml-modules/root/state-conductor/tasks/waitTask.sjs
  state-conductor-modules/src/main/ml-modules/root/state-conductor/trigger/state-conductor-item-trigger.sjs
Labels: bug

#111 Merge pull request #82 from aclavio/develop
  state-conductor-example/src/test/ml-modules/root/test/suites/StateConductorSuite/provenanceTests.sjs
  state-conductor-example/src/test/ml-modules/root/test/suites/StateConductorSuite/resumeWaitingJobByJobDoc-tests.sjs
  state-conductor-modules/src/main/ml-modules/root/state-conductor/state-conductor.sjs
Labels: bug, enhancement
